# ref: https://themes.gohugo.io/themes/hugo-coder/#quick-start
baseurl = "https://mokuo.me"
title = "mokuo"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

# ref: https://molina.jp/blog/hugo%E3%81%A6%E6%9B%B4%E6%96%B0%E6%97%A5%E6%99%82%E3%81%AE%E7%AE%A1%E7%90%86/
enableGitInfo = true

[params]
  author = "mokuo"
  info = "Web Developer"
  description = "mokuo's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  #gravatar = "john.doe@example.com"

  favicon_32 = "favicon-32x32.png"
  favicon_16 = "favicon-16x16.png"

  since = 2020

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

# [taxonomies]
#   category = "categories"
#   series = "series"
#   tag = "tags"
#   author = "authors"

[params.googleTagManager]
    id = "G-CKQWD8HKLV"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/mokuo/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 2
  url = "https://twitter.com/mokuo_/"

# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"
[[menu.main]]
  name = "Products"
  weight = 2
  url  = "products/"
# [[menu.main]]
#   name = "Blog"
#   weight = 3
#   url  = "posts/"
